name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: petroleum

env:
  HUSKY: 0

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Get SSH private key from SSM
        id: get-ssh-key
        run: |
          SSH_KEY=$(aws ssm get-parameter --name "/ministries/petroleum/ssh/private-key" --with-decryption --query 'Parameter.Value' --output text)
          echo "SSH_KEY<<EOF" >> $GITHUB_ENV
          echo "$SSH_KEY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: |
          gem install kamal -v 2.2.2

      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Lock release
        run: kamal lock release

      - name: Prune unused resources
        run: kamal prune all; docker system prune -f

      - name: Deploy to Production
        run: kamal setup || kamal deploy
        env:
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
          NEXT_PUBLIC_MINISTRY_ID: ${{ secrets.NEXT_PUBLIC_MINISTRY_ID }}
          NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
          NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
          NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
